project2/employee/urls.py
from django.urls import path
from . import views

app_name = 'employee'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

project2/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='index')
]

project2/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('main/', include('main.urls')),
]

project2/employee/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator, MinLengthValidator

class Department(models.Model):
    name = models.CharField('配属先', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)
    
    def __str__(self):
        return self.name
        

class Status(models.Model):
    name = models.CharField('雇用形態', max_length=20)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Employee(models.Model):
    first_name = models.CharField('名', max_length=20)
    last_name = models.CharField('姓', max_length=20)
    
    sex = models.CharField('性別', max_length=20)
    
    id_regex = RegexValidator(regex=r'^\d{4}$',message=("IDは半角数字４桁で入力してください."))
    id = models.CharField('ID', max_length=20, primary_key=True , validators=[id_regex])
    
    ##入力のみ
    
    # ハイフンを含むフォーマットに対応
    phone_number_regex = RegexValidator(regex=r'^\d{2,4}-\d{2,4}-\d{4}$',  message=("電話番号は「090-1234-5678」の形式で入力してください."))
    phone_number = models.CharField('電話番号', max_length=13,validators=[phone_number_regex]) 
    
    password_regex = RegexValidator(regex=r'^[a-zA-Z0-9]+$',  message=("パスワードは半角英数字で入力してください."))
    password = models.CharField('パスワード',  max_length=15, validators=[password_regex, MinLengthValidator(8, message="パスワードは8桁以上で入力してください。")])
    
    department = models.ForeignKey(
        Department, verbose_name='配属', on_delete=models.PROTECT,
    )
    status = models.ManyToManyField(
        Status, verbose_name='雇用形態',
    )
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return '{0} {1} {2} {3} {4} {5} {6}'.format(self.last_name, self.first_name, self.department, self.sex, self.phone_number, self.password, self.id)
    

    #messi

##mbappe

project2/main/models.py
from django.db import models

# Create your models here.

project2/employee/forms.py
from django import forms
from .models import Status, Department


class SearchForm(forms.Form):
    status = forms.ModelChoiceField(
        queryset=Status.objects, label='雇用形態', required=False)

    department = forms.ModelChoiceField(
        queryset=Department.objects, label='配属', required=False)

project2/employee/views.py
from django.views import generic
from .forms import SearchForm
from .models import Employee


class IndexView(generic.ListView):
    model = Employee
    paginate_by = 5

    def get_context_data(self):
        """テンプレートへ渡す辞書の作成"""
        context = super().get_context_data()
        context['form'] = SearchForm(self.request.GET)   # 基の辞書に、formを追加
        return context

    def get_queryset(self):
        """テンプレートへ渡す「employee_list」を作成する"""
        form = SearchForm(self.request.GET)
        form.is_valid()  # これをしないと、cleaned_dataができない!!!

        # まず、全社員を取得
        queryset = super().get_queryset()

        # 部署の選択があれば、部署で絞り込み(filter)
        department = form.cleaned_data['department']
        if department:
            queryset = queryset.filter(department=department)

        # サークルの選択があれば、サークルで絞り込み(filter)
        status = form.cleaned_data['status']
        if status:
            queryset = queryset.filter(status=status)
        return queryset

project2/main/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main/main.html')

project2/employee/templates/employee/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>社員管理システム</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    {% block extracss %}
    {% endblock %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'main:index' %}">社員管理システム</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'employee:index' %}">一覧</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:employee_employee_add' %}">社員追加</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    {% block extrajs %}
    {% endblock %}
  </body>
</html>

project2/employee/templates/employee/employee_list.html
{% extends 'employee/base.html' %}

{% block content %}

<form action="" method="GET" class="form-inline mt-2 mb-3">
  {{ form }}  
  <button type="submit" class="btn btn-primary ml-2 mt-3">
    <i class="fas fa-search"></i> 検索</button>
  
</form>

<div class="table-responsive">
<table class="table table-bordered table-hover mt-4">
  <thead class="thead-light">
    <tr>
      <th>ID</th>
      <th>姓</th>
      <th>名</th>
      <th>性別</th>
      <th>配属</th>
      <th>雇用形態</th>
      <th>パスワード</th>
      <th>電話番号</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employee_list %}
    <tr>
      <td>{{ employee.id }}</td>
      <td>{{ employee.last_name }}</td>
      <td>{{ employee.first_name }}</td>
      <td>{{ employee.sex }}</td>
      <td>{{ employee.department }}</td>
      <td>{% for status in employee.status.all %}{{ status }} {% endfor %}</td>
      <td>{{ employee.password }}</td>
      <td>{{ employee.phone_number }}</td>

      <td>
        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#employeeModal{{ employee.id }}">
          詳細
        </button>
      </td>
    </tr>


    <!--詳細のクラス-->
    <div class="modal fade" id="employeeModal{{ employee.id }}" tabindex="-1" role="dialog" aria-labelledby="employeeModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="employeeModalLabel">{{ employee.first_name }} {{ employee.last_name }} の詳細</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p><strong>性別:</strong> {{ employee.sex }}</p>
            <p><strong>配属:</strong> {{ employee.department }}</p>
            <p><strong>雇用形態:</strong> {% for status in employee.status.all %}{{ status }} {% endfor %}</p>
            <p><strong>電話番号:</strong> {{ employee.phone_number }}</p>
            <!-- 他の詳細情報を追加 -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          </div>
        </div>
      </div>
    </div>


    
    {% endfor %}
  </tbody>
</table>
</div>


{% include 'employee/page5.html' %}



{% endblock %}

project2/employee/templates/employee/page5.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

project2/main/templates/main/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>社員管理システム</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'main:index' %}">社員管理システム</a>
      
    
      
    </nav>
    
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

project2/main/templates/main/main.html
{% extends 'main/base.html' %}

{% block content %}
<h1>メインページ（仮）</h1>
{% endblock %}
